CREATE TABLE IF NOT EXISTS `sources` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `source` VARCHAR(255) NOT NULL,
    `description` TEXT,
    `url` VARCHAR(2083),
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `uniq_source` (`source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


